# permissions for end users to view syncconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmapsyncer
    app.kubernetes.io/managed-by: kustomize
  name: syncconfig-viewer-role
rules:
- apiGroups:
  - muhu3.example.com
  resources:
  - syncconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - muhu3.example.com
  resources:
  - syncconfigs/status
  verbs:
  - get
