# permissions for end users to edit syncconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmapsyncer
    app.kubernetes.io/managed-by: kustomize
  name: syncconfig-editor-role
rules:
- apiGroups:
  - muhu3.example.com
  resources:
  - syncconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - muhu3.example.com
  resources:
  - syncconfigs/status
  verbs:
  - get
