apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: configmapsyncer
    app.kubernetes.io/managed-by: kustomize
  name: syncconfig-editor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: syncconfig-editor-role
subjects:
- kind: ServiceAccount
  name: configmapsyncer-controller-manager
  namespace: default